name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    tags-ignore: ["*"]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Actions'
      uses: actions/checkout@v4
      with:
        fetch-depth: 5
        fetch-tags: true

    - name: 'Build the Docker image'
      run: IMAGE_REPO=ghcr.io make docker

    - name: 'Test the Docker image'
      run: IMAGE_REPO=ghcr.io make docker_test
